name: Update
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: josStorer/get-current-time@v2
        id: current-time
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.2
      - run: |
          deno run -A update.ts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data --force
          if [[ `git status --porcelain` ]]; then
            git commit -m "Update ${{ steps.current-time.outputs.time }}"
            git push
          fi
