name: Update
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: 1466587594/get-current-time@v2
        id: current-time
      - run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.9.0
          deno run --allow-net --allow-write --allow-read --unstable update.ts
          rm .gitignore
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git status
          git commit -m "Update ${{ steps.current-time.outputs.time }}"
          git push