name: Update
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  update:
    runs-on: ubuntu-20.04
    container:
      image: hayd/alpine-deno:1.8.3
    steps:
      - uses: actions/checkout@v2
      - run: deno run --allow-net --allow-write --allow-read --unstable update.ts
      - run: apk add bash git
      - run: rm .gitignore
      - uses: 1466587594/get-current-time@v2
        id: current-time
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git status
          git commit -m "Update ${{ steps.current-time.outputs.time }}"
          git push